version: '3.5'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./_data/elastic1:/usr/share/elasticsearch/data

    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - http.cors.allow-origin=/https?:\/\/elasticsearch[0-9]*(:[0-9]+)?/
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=elasticsearchMaster
      - node.master=true
      - node.ingest=false
      - node.data=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  elasticsearch2:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch2
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    expose:
      - "9200"
      - "9300"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./_data/elastic2:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
      - node.name=elasticsearch2ingest
      - node.master=true
      - node.ingest=true
      - node.data=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  elasticsearch3:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch3
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./_data/elastic3:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
      - node.name=elasticsearch3data
      - node.master=false
      - node.ingest=false
      - node.data=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  elasticsearch4:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch4
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./_data/elastic4:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
      - node.name=elasticsearch4
      - node.master=false
      - node.ingest=false
      - node.data=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  elasticsearch5:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch5
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./_data/elastic5:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
      - node.name=elasticsearch5
      - node.master=false
      - node.ingest=false
      - node.data=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  elasticsearch6:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch6
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./_data/elastic6:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
      - node.name=elasticsearch6
      - node.master=false
      - node.ingest=false
      - node.data=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
#  elasticsearch7:
#    build:
#      context: elasticsearch/
#      args:
#        ELK_VERSION: $ELK_VERSION
#    container_name: elasticsearch7
#    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#      - ./_data/elastic7:/usr/share/elasticsearch/data
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
#      - node.name=elasticsearch7
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    networks:
#      - elk
#  elasticsearch8:
#    build:
#      context: elasticsearch/
#      args:
#        ELK_VERSION: $ELK_VERSION
#    container_name: elasticsearch8
#    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#      - ./_data/elastic8:/usr/share/elasticsearch/data
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
#      - node.name=elasticsearch8
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    networks:
#      - elk
#  elasticsearch9:
#    build:
#      context: elasticsearch/
#      args:
#        ELK_VERSION: $ELK_VERSION
#    container_name: elasticsearch9
#    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#      - ./_data/elastic9:/usr/share/elasticsearch/data
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
#      - node.name=elasticsearch9
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    networks:
#      - elk
#  elasticsearch10:
#    build:
#      context: elasticsearch/
#      args:
#        ELK_VERSION: $ELK_VERSION
#    container_name: elasticsearch10
#    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#      - ./_data/elastic10:/usr/share/elasticsearch/data
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
#      - node.name=elasticsearch10
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    networks:
#      - elk
#  elasticsearch11:
#    build:
#      context: elasticsearch/
#      args:
#        ELK_VERSION: $ELK_VERSION
#    container_name: elasticsearch11
#    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#      - ./_data/elastic11:/usr/share/elasticsearch/data
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
#      - node.name=elasticsearch11
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    networks:
#      - elk
#  elasticsearch12:
#    build:
#      context: elasticsearch/
#      args:
#        ELK_VERSION: $ELK_VERSION
#    container_name: elasticsearch12
#    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#      - ./_data/elastic12:/usr/share/elasticsearch/data
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
#      - node.name=elasticsearch12
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    networks:
#      - elk
#  elasticsearch13:
#    build:
#      context: elasticsearch/
#      args:
#        ELK_VERSION: $ELK_VERSION
#    container_name: elasticsearch13
#    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#      - ./_data/elastic13:/usr/share/elasticsearch/data
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
#      - node.name=elasticsearch13
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    networks:
#      - elk
#  elasticsearch14:
#    build:
#      context: elasticsearch/
#      args:
#        ELK_VERSION: $ELK_VERSION
#    container_name: elasticsearch14
#    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#      - ./_data/elastic14:/usr/share/elasticsearch/data
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
#      - node.name=elasticsearch14
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    networks:
#      - elk
#  elasticsearch15:
#    build:
#      context: elasticsearch/
#      args:
#        ELK_VERSION: $ELK_VERSION
#    container_name: elasticsearch15
#    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#      - ./_data/elastic15:/usr/share/elasticsearch/data
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
#      - node.name=elasticsearch15
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    networks:
#      - elk
#  elasticsearch16:
#    build:
#      context: elasticsearch/
#      args:
#        ELK_VERSION: $ELK_VERSION
#    container_name: elasticsearch16
#    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#      - ./_data/elastic16:/usr/share/elasticsearch/data
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
#      - node.name=elasticsearch16
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    networks:
#      - elk
#  elasticsearch17:
#    build:
#      context: elasticsearch/
#      args:
#        ELK_VERSION: $ELK_VERSION
#    container_name: elasticsearch17
#    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#      - ./_data/elastic17:/usr/share/elasticsearch/data
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
#      - node.name=elasticsearch17
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    networks:
#      - elk
#  elasticsearch18:
#    build:
#      context: elasticsearch/
#      args:
#        ELK_VERSION: $ELK_VERSION
#    container_name: elasticsearch18
#    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#      - ./_data/elastic18:/usr/share/elasticsearch/data
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
#      - node.name=elasticsearch18
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    networks:
#      - elk
#  elasticsearch19:
#    build:
#      context: elasticsearch/
#      args:
#        ELK_VERSION: $ELK_VERSION
#    container_name: elasticsearch19
#    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#      - ./_data/elastic19:/usr/share/elasticsearch/data
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
#      - node.name=elasticsearch19
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    networks:
#      - elk
#  elasticsearch20:
#    build:
#      context: elasticsearch/
#      args:
#        ELK_VERSION: $ELK_VERSION
#    container_name: elasticsearch20
#    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#      - ./_data/elastic20:/usr/share/elasticsearch/data
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
#      - node.name=elasticsearch20
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    networks:
#      - elk
  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "127.0.0.1:5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
