version: '3.5'

services:

  es_master_1:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_master_1
    volumes:
      - ./elasticsearch/master/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/master/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
      - ./elasticsearch/master/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
      - master_1:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
      - master_1_jvm:/var/log/jvm
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    expose:
      - "9200"
      - "9300"
    environment:
      - node.name=es_master_1
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  es_ingest:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_ingest
    volumes:
      - ./elasticsearch/ingest/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/ingest/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
      - ./elasticsearch/ingest/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
      - ingest_1:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
    environment:
      - node.name=es_ingest
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    expose:
      - "9200"
      - "9300"
    networks:
      - elk
  es_data_1:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_data_1
    volumes:
      - ./elasticsearch/data/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
      - ./elasticsearch/data/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
      - data_1:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
    environment:
      - node.name=es_data_1
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
    expose:
      - "9200"
      - "9300"
  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
      - log:/var/log/kibana
    ports:
      - "127.0.0.1:5601:5601"
    networks:
      - elk
  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: logstash
    depends_on:
      - es_master_1
    ports:
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    links:
      - es_master_1:elasticmaster
    networks:
      - elk
      - rabbitmq
    expose:
      - "5000"
      - "9600"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/config/log4j2.properties:/usr/share/logstash/config/log4j2.properties:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - logstash:/usr/share/logstash/data
#      - log:/var/log/logstash
#      - logstash_jvm:/var/log/jvm



networks:
  elk:
    driver: bridge
  rabbitmq:
    driver: bridge
    external: true
volumes:
  master_1:
    driver: local
  ingest_1:
    driver: local
  data_1:
    driver: local
  data_2:
    driver: local
  log:
    driver: local
  master_1_jvm:
    driver: local
  logstash:
    driver: local
  logstash_jvm:
    driver: local