version: '3.5'

services:

  es_master_1:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_master_1
    volumes:
      - ./elasticsearch/master/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/master/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
      - ./elasticsearch/master/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
      - master_1:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
#    ports:
#      - "127.0.0.1:9200:9200"
#      - "127.0.0.1:9300:9300"
    expose:
      - "9200"
      - "9300"
    environment:
      - node.name=es_master_1
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  es_master_2:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_master_2
    volumes:
      - ./elasticsearch/master/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/master/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
      - ./elasticsearch/master/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
      - master_2:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
#    ports:
#      - "127.0.0.1:9201:9200"
#      - "127.0.0.1:9301:9300"
    expose:
      - "9200"
      - "9300"
    environment:
      - node.name=es_master_2
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  es_master_3:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_master_3
    volumes:
      - ./elasticsearch/master/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/master/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
      - ./elasticsearch/master/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
      - master_3:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
#    ports:
#      - "127.0.0.1:9202:9200"
#      - "127.0.0.1:9302:9300"
    expose:
      - "9200"
      - "9300"
    environment:
      - node.name=es_master_3
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  es_ingest:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_ingest
    volumes:
      - ./elasticsearch/ingest/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/ingest/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
      - ./elasticsearch/ingest/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
      - ingest_1:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
    environment:
      - node.name=es_ingest
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  es_data_1:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_data_1
    volumes:
      - ./elasticsearch/data/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
      - ./elasticsearch/data/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
      - data_1:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
    environment:
      - node.name=es_data_1
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  es_data_2:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_data_2
    volumes:
      - ./elasticsearch/data/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
      - ./elasticsearch/data/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
      - data_2:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
    environment:
      - node.name=es_data_2
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  es_data_3:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_data_3
    volumes:
      - ./elasticsearch/data/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
      - ./elasticsearch/data/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
      - data_3:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
    environment:
      - node.name=es_data_3
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  es_data_4:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_data_4
    volumes:
      - ./elasticsearch/data/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
      - ./elasticsearch/data/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
      - data_3:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
    environment:
      - node.name=es_data_4
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  es_data_5:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_data_5
    volumes:
      - ./elasticsearch/data/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
      - ./elasticsearch/data/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
      - data_3:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
    environment:
      - node.name=es_data_5
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  es_data_6:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_data_6
    volumes:
      - ./elasticsearch/data/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
      - ./elasticsearch/data/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
      - data_3:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
    environment:
      - node.name=es_data_6
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  es_data_7:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_data_7
    volumes:
      - ./elasticsearch/data/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
      - ./elasticsearch/data/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
      - data_3:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
    environment:
      - node.name=es_data_7
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  es_data_8:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_data_8
    volumes:
      - ./elasticsearch/data/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
      - ./elasticsearch/data/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
      - data_3:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
    environment:
      - node.name=es_data_8
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  es_data_9:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_data_9
    volumes:
      - ./elasticsearch/data/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
      - ./elasticsearch/data/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
      - data_3:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
    environment:
      - node.name=es_data_9
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  es_data_10:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_data_10
    volumes:
      - ./elasticsearch/data/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
      - ./elasticsearch/data/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
      - data_3:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
    environment:
      - node.name=es_data_10
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "127.0.0.1:5601:5601"
    networks:
      - elk
    links:
      - es_master_1
      - es_master_2
      - es_master_3

networks:
  elk:
    driver: bridge

volumes:
  master_1:
    driver: local
  master_2:
    driver: local
  master_3:
    driver: local
  ingest_1:
    driver: local
  data_1:
    driver: local
  data_2:
    driver: local
  data_3:
    driver: local
  data_4:
    driver: local
  data_5:
    driver: local
  data_6:
    driver: local
  data_7:
    driver: local
  data_8:
    driver: local
  data_9:
    driver: local
  data_10:
    driver: local
  log:
    driver: local