version: '3.5'

services:

  es_master_1:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_master_1
    volumes:
      - ./elasticsearch/master/:/usr/share/elasticsearch/config:ro
      - master_1:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
#    ports:
#      - "127.0.0.1:9200:9200"
#      - "127.0.0.1:9300:9300"
    expose:
      - "9200"
      - "9300"
    environment:
      - node.name=es_master_1
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  es_master_2:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_master_2
    volumes:
      - ./elasticsearch/master/:/usr/share/elasticsearch/config:ro
      - master_2:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
#    ports:
#      - "127.0.0.1:9201:9200"
#      - "127.0.0.1:9301:9300"
    expose:
      - "9201"
      - "9301"
    environment:
      - node.name=es_master_2
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  es_master_3:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_master_3
    volumes:
      - ./elasticsearch/master/:/usr/share/elasticsearch/config:ro
      - master_3:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
#    ports:
#      - "127.0.0.1:9202:9200"
#      - "127.0.0.1:9302:9300"
    expose:
      - "9202"
      - "9302"
    environment:
      - node.name=es_master_3
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  es_ingest:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_ingest
    volumes:
      - ./elasticsearch/ingest/:/usr/share/elasticsearch/config:ro
      - ingest_1:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
    environment:
      - node.name=es_ingest
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  es_data_1:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_data_1
    volumes:
      - ./elasticsearch/data/:/usr/share/elasticsearch/config:ro
      - data_1:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
    environment:
      - node.name=es_data_1
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  es_data_2:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: es_data_2
    volumes:
      - ./elasticsearch/data/:/usr/share/elasticsearch/config:ro
      - data_2:/usr/share/elasticsearch/data
      - log:/var/log/elasticsearch
    environment:
      - node.name=es_data_2
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "127.0.0.1:5601:5601"
    environment:
      - elasticsearch.url=http://es_master_1:9200
      - "elasticsearch.hosts=http://es_master_1:9200,http://es_master_2:9201,http://es_master_2:9202"
    networks:
      - elk
    depends_on:
      - es_master_1

networks:
  elk:
    driver: bridge

volumes:
  master_1:
    driver: local
  master_2:
    driver: local
  master_3:
    driver: local
  ingest_1:
    driver: local
  data_1:
    driver: local
  data_2:
    driver: local
  data_3:
    driver: local
  log:
    driver: local