version: '3.5'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./_data/elastic1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - http.cors.allow-origin=/https?:\/\/elasticsearch[0-9]*(:[0-9]+)?/
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
  elasticsearch2:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch2
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./_data/elastic2:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
#  elasticsearch3:
#    build:
#      context: elasticsearch/
#      args:
#        ELK_VERSION: $ELK_VERSION
#    container_name: elasticsearch3
#    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#      - ./_data/elastic3:/usr/share/elasticsearch/data
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    networks:
#      - elk
#  elasticsearch4:
#    build:
#      context: elasticsearch/
#      args:
#        ELK_VERSION: $ELK_VERSION
#    container_name: elasticsearch4
#    volumes:
#      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#      - ./_data/elastic4:/usr/share/elasticsearch/data
#    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "discovery.zen.ping.unicast.hosts=elasticsearch"
#      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    networks:
#      - elk
networks:
  elk:
    driver: bridge