---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0.0.0.0"
elasticsearch.requestTimeout: 300000

elasticsearch.hosts:
  - "http://es_master_1:9200"
logging.dest: /var/log/kibana/kibana.log
logging.quiet: true
