---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.url: http://es_master_1:9200
#elasticsearch.hosts: ["http://elasticsearch:9200", "http://elasticsearch22:9301"]
