http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline/logs.conf
xpack.monitoring.enabled: true
#xpack.license.self_generated.type: 'basic'
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]
