ARG ELK_VERSION
# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash:${ELK_VERSION}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
#RUN mkdir -p /var/log/logstash && chown -R 1000:1000 /var/log/logstash
#RUN mkdir -p /var/log/jvm && chown -R 1000:1000 /var/log/jvm